const ActionTypes = {
    // Categories All
    CATEGORIES_ALL_REQ: "CATEGORIES_ALL_REQ",
    CATEGORIES_ALL_OK: "CATEGORIES_ALL_OK",
    CATEGORIES_ALL_X: "CATEGORIES_ALL_X",
    //Category add
    CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
    CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
    CATEGORY_ADD_X: "CATEGORY_ADD_X",
    //Delete category
    CATEGORY_DELETE_REQ: "CATEGORY_DELETE_REQ",
    CATEGORY_DELETE_OK: "CATEGORY_DELETE_OK",
    CATEGORY_DELETE_X: "CATEGORY_DELETE_X",
    //FILTER CATEGORIES BY BUDGET LIMIT(SIMILAR TO CATEGORIES ALL, BUT WE GET ONLY RESULTS BY ID)
    CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_REQ: "CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_REQ",
    CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_OK: "CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_OK",
    CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_X: "CATEGORIES_FILTER_BY_BUDGET_LIMIT_FILTER_X"
  };
  
  export default ActionTypes;